%%{init: {'themeVariables': { 'primaryColor': '#999999', 'lineColor': '#999999'}}}%%

%% Common class definitions
classDef stateNode fill:#f3f0ff,stroke:#9b4dca,stroke-width:2px,color:#000000
classDef processNode fill:#f3f0ff,stroke:#9b4dca,stroke-width:2px,color:#000000,rx:2
classDef decisionNode fill:#f3f0ff,stroke:#9b4dca,stroke-width:2px,color:#000000,shape:diamond
classDef eventNode fill:#f3f0ff,stroke:#9b4dca,stroke-width:2px,color:#000000,shape:circle
